version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_legal
    restart: always
    environment:
      POSTGRES_USER: legal_user
      POSTGRES_PASSWORD: legal_pass
      POSTGRES_DB: legal_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
